# Parent compose file: $(git root)/compose.yaml

# Exposes a Neo4j graph database on port 7687 (Bolt)
# and its HTTP interface at http://localhost:7474.

services:
  neo4j:
    image: neo4j:5-community
    container_name: polyglot-dtp-neo4j
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-dtpsecret1}
    ports:
      - "127.0.0.1:7474:7474"
      - "[::1]:7474:7474"
      - "127.0.0.1:7687:7687"
      - "[::1]:7687:7687"
    networks:
      - default
    volumes:
      - neo4jdata:/data
    healthcheck:
      test: ["CMD-SHELL", "neo4j status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  neo4jdata:
    name: polyglot-dtp_neo4jdata
