services:
  mock-sensor-1:
    image: yinchi/mock-sensor:latest
    container_name: polyglot-dtp-mock-sensor-1
    build:
      context: ../../
      dockerfile: pypackages/mock_sensor/Dockerfile
    restart: always
    depends_on:
      # From infra/mqtt/compose.include.yaml
      mosquitto:
        condition: service_healthy
    env_file:
      - mqtt.env
    volumes:
      - ./sensor.yaml:/app/sensor.yaml:ro
    command:
      - --config
      - /app/sensor.yaml
    networks:
      - iot
