services:
  twins-test:
    build:
      context: ../../
      dockerfile: pypackages/twins_test/Dockerfile
    container_name: polyglot-dtp-twins-test
    environment:
      - TWIN_TEST_FOO=${TWIN_TEST_FOO:-default_foo}
    networks:
      - default
    ports:
      - "8000:8000"
    healthcheck:
      # Use the single API endpoint to check service health
      test: ["CMD-SHELL", "curl -sf http://localhost:8000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
