[project]
name = "dev-docs"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-kroki-plugin>=0.9.0",
    "mkdocs-material>=9.6.21",
    "pymdown-extensions>=10.16.1",
]
